### ISSUE TITLE
libraries versions and results

### ISSUE THREAD

**Issue by 673402618** [CAOR-MINES-ParisTech/lwoi#2]
1.I wonder which version of the 3rd party library you use. The function "gp.likelihood.Gaussian" in development branch of pyro doesn't has a parameter called "name".
2.I run this program with default parameters. But the result shows that the corrected model dosen't work well on most training datasets. Can you provide a set of parameters to get results as shown in the paper ?

**Comment by paulwong16** [comment]
The following are my libs versions which works on my pc(ubuntu 16.04)

liegroups 1.0.0
numpy 1.16.2
progressbar2 3.39.2
pyro-ppl 0.2.0+f5b7e6d
scipy 1.2.1
torch 1.0.1.post2

https://github.com/paulwong16/lwoi/blob/master/ThirdPartyVersion.md

**Comment by paulwong16** [comment]
> 1.I wonder which version of the 3rd party library you use. The function "gp.likelihood.Gaussian" in development branch of pyro doesn't has a parameter called "name".
> 2.I run this program with default parameters. But the result shows that the corrected model dosen't work well on most training datasets. Can you provide a set of parameters to get results as shown in the paper ?

Here are my libs versions which work on my pc(ubuntu 16.04)

liegroups 1.0.0
numpy 1.16.2
progressbar2 3.39.2
pyro-ppl 0.2.0+f5b7e6d
scipy 1.2.1
torch 1.0.1.post2

https://github.com/paulwong16/lwoi/blob/master/ThirdPartyVersion.md

**Comment by mbrossar** [comment]
Sorry for late answer.

This is the version that I used:
liegroups 1.0.0
numpy 1.16.2
progressbar2 3.39.2
pyro-ppl 0.3.0+f5b7e6d
scipy 1.2.1
torch 1.0.1.post2

I now see that I did minor modifications in my pyro lib (e.g. the name that is used only for saving). I will update the code soon. I will also see why it does not work well. Normally you observe for almost all dataset a similar improvement.

**Comment by mbrossar** [comment]
As paulwong16 notices, the most simple way to run the code is to install the pyro-ppl 0.2.0+f5b7e6d and not the last version.
